### ISSUE TITLE
Missing window buttons in non-GTK3 applications in GNOME 3.16 (Fedora 22)

### ISSUE THREAD

**Issue by danielkza** [horst3180/Vertex-theme#107]
I'm using the F21 repository to get Vertex in F22, and it seems the window buttons (minimize, maximize and close) are invisible in all but GTK3 apps. Check out the following screenshot: GParted uses GTK2, VLC uses Qt, and GNOME Tweak tool uses GTK3, and only Tweak Tool shows the buttons.

![screenshot from 2015-05-31 16-37-55](https://cloud.githubusercontent.com/assets/747342/7903476/d5c45956-07b3-11e5-8004-eb7bac18b1d5.png)

I can't find anything that looks like a theme-related error in the system log, but I have a lot of noise so I might just be missing it.

Package versions:

vertex-theme: 1429980512.e1878d2-11.1
gtk3: 3.16.3-1.fc22
gtk2: 2.24.28-1.fc22
gtk-murrine-engine: 0.98.2-7.fc22
gnome-desktop3: 3.16.2-1.fc22

**Comment by horst3180** [comment]
Yeah, unfortunately the opensuse build service still hasn't enabled Fedora 22 build support. Your problem is exactly what happens when you use the 3.14 version of the theme in Gnome 3.16. If you want to have it working right now without waiting for open build service you'll have to install the theme manually. Make sure to uninstall the package before you do it.

**Comment by danielkza** [comment]
Alright, I'll do that for now. Does the new version break on GNOME 3.14? If it doesn't, you could push to the F21 repo as well. Either way, since it's already fixed, I consider it addressed. Thanks!

**Comment by horst3180** [comment]
Some things break unfortunately and I can't make it compatible with 3.14 and 3.16 at the same time.

**Comment by horst3180** [comment]
Fedora 22 packages are now available.
