### ISSUE TITLE
Elements boxes

### ISSUE THREAD

**Issue by dege1000** [horst3180/Vertex-theme#118]
With the dark theme some windows have boxes on every single element witch to be fair is really annoying, do you have any idea why?
![image](https://cloud.githubusercontent.com/assets/10297001/9024538/0166929a-38ab-11e5-9cee-6c7c6dab008e.png)
![image](https://cloud.githubusercontent.com/assets/10297001/9024542/5caf11c2-38ab-11e5-9e97-02bf3b1f037f.png)

**Comment by horst3180** [comment]
Which distro are you using and how did you install the theme?

**Comment by dege1000** [comment]
I use Linux Mint 17.2 and I installed it cloning the git and using sudo make install

**Comment by horst3180** [comment]
Hmm it looks like it installed the wrong version of the theme. Please check the build dependencies described in the readme.
I suggest that you install the package for Ubuntu 14.04 from [here](http://software.opensuse.org/download.html?project=home%3AHorst3180&package=vertex-theme) instead, because it will recieve automatic updates and will be easier to install.

**Comment by dege1000** [comment]
Ok thanks for the help
