### ISSUE TITLE
Dashed lines around elements

### ISSUE THREAD

**Issue by erikdubois** [horst3180/Vertex-theme#161]
I just wrote an article at http://erikdubois.be/how-to-completely-install-all-aspects-of-the-vertex-dark-theme-on-linux-mint-17-3/ about your theme.
In linux mint 17.3 Cinnamon it shows up rather ugly. Check out the article to see what I mean.

I posted the work-around.

/usr/share/themes/Vertex-Dark/gtk-3.0/tk-contained.css
change 
outline-style: dashed;
to
outline-style: none;
Hope this helps to improve your theme.

**Comment by horst3180** [comment]
That workaround shouldn't be necessary. Do you have the `libgtk-3-dev` and `pkg-config` packages installed? They're used to detect the GTK version and install the correct version of the theme.

But the easiest way to install the theme is to use the [package repo](https://software.opensuse.org/download.html?project=home%3AHorst3180&package=vertex-theme). Since Mint uses GTK 3.10, the package for Ubuntu 14.04 should work fine.

You'll have to remove the `/usr/share/Vertex*` folders if you have already installed the theme manually and want to use the packages instead, i.e.

    sudo rm -rf /usr/share/themes/{Vertex,Vertex-Dark,Vertex-Light,Vertex-Gnome-Shell,Vertex-Gnome-Shell-3.16,Vertex-Cinnamon}

Under the link you find instructions on how to add the repo for Ubuntu 14.04, but I'll past them here really quick

    sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/vertex-theme.list"
    sudo apt-get update
    sudo apt-get install vertex-theme

Optional: Import the keys

    wget http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_14.04/Release.key
    sudo apt-key add - < Release.key

**Comment by erikdubois** [comment]
thanks I will check that out and let you know

**Comment by erikdubois** [comment]
Hi Horst,

installed it on a clean install machine
github way
but this time with libgtk-3-dev
it could not have been pkg-config since that was up to date.
so the issue was libgtk-3-dev.
I know i should have read better 
maybe you could change the lines 
libgtk-3-dev for Debian based distros or gtk3-devel for RPM based distros
into
libgtk-3-dev for Debian based distros (Ubuntu, Linux Mint, ...) or gtk3-devel for RPM based distros (Fedora, ...)
or something of that kind
anyway thanks for your help and I will change my article accordingly
