### ISSUE TITLE
Thunderbird - large space after close button on tab

### ISSUE THREAD

**Issue by vantu5z** [horst3180/Vertex-theme#42]
Firefox and Thunderbird tabs looks quadratic. May be make it more round?
I try to make something with Thunderbird tab and rounded right corner:
![screen_tab_thunderbird](https://cloud.githubusercontent.com/assets/8698003/5695592/eebc06f8-99bc-11e4-8ff9-361cd8daad69.png)

May be it seems to me quadratic after default, but in my opinion little more round looks nicer (just right or both).

Anyway i think that space on tab beetwen 'x' and next tab need to be reduced.

**Comment by manoevis** [comment]
no, rounding is ugly, this is why I use this theme - cause it have nice colors and no rounding.

**Comment by vantu5z** [comment]
ok, and what do you think about large space after close button on tab?

**Comment by manoevis** [comment]
Firefox doesn't have it.
![tab_close](https://cloud.githubusercontent.com/assets/5586135/5719423/1d428db6-9b21-11e4-98f3-b1cc882d08ba.png)

Thunderbird I don't use. But I've checked, and it seems it's a bug or theme can't do otherwise. That space looks kinda ugly. I would fix that and I'll do that if I use Thunderbird at some point.

**Comment by vantu5z** [comment]
Thanks in advance! ;)
Suppose i can remove round question from topic and change it by space.
