### ISSUE TITLE
Epiphany (GNOME Web) in private browsing mode is unthemed

### ISSUE THREAD

**Issue by aperezdc** [horst3180/Vertex-theme#59]
Dunno if this is lack of theming, or wrong theming:

![Epiphany in private browsing mode](http://i.imgur.com/vFHkqtT.png)

The light variant of the theme does not look that bad because the light tones blend reasonably well with the alternate styling of the browser windows that is done by the browser.

Hopefully this can get fixed easily. One idea that comes to mind is using styles from the light variant of the theme for private browsing mode windows.

If there is something I can do to help you fix this issue, please let me know and I'll be happy to help.

**Comment by horst3180** [comment]
Hi, I've tried to fix that in the past, but with no success. The problem is, that epiphany loads a stylesheet for incognito which overrides the theme. The exact same bug shows when using Adwaita dark
![epiphany](https://cloud.githubusercontent.com/assets/8473629/6579535/16697580-c74b-11e4-8deb-4a313d53b919.png)

Using the light style for private browsing mode windows would require quite some work and would mean that I would have to duplicate a lot of code, which makes the theme harder to maintain and I would rather not do it just for one application.

I think the bug here is on epiphany's side. It should only load the stylesheet when using Adwaita (Gedit does this for example) and it should be made compatible with the dark variant, by using non hardcoded colors, derived from the theme.

**Comment by aperezdc** [comment]
@horst3180: Good to know about all this. It turns out there is a [bug reported in Epiphany](https://bugzilla.gnome.org/show_bug.cgi?id=742088) already for this. I am going to comment there linking to this issue, so developers can see the suggestion about only loading the custom theme with the normal (non-dark) Adwaita. That way other themes will look better.

**Comment by horst3180** [comment]
Thanks, maybe this will get some attention.
