### ISSUE TITLE
[bug] [g3.16] Window's close button

### ISSUE THREAD

**Issue by manoevis** [horst3180/Vertex-theme#80]
I see this button for chrome all the time. Where is that fancy red dot?
![selection_002](https://cloud.githubusercontent.com/assets/5586135/6983726/132bc99e-da2a-11e4-99fe-3b99690e9039.png)

System:
  - Ubuntu 15.04 beta (2015/04/03 updates)
  - gnome 3.16 (from gnome-staging ppa)
  - vertex-dark for gnome-3.16 (latest from git repo)

**Comment by horst3180** [comment]
The colored buttons have been replaced by new ones for 3.16. However, they should look like the csd buttons when you are not hovering over them with your mouse.
I have the same bug on Arch Linux, but I don't think it's theme related, because it works on my Fedora 22 vm and on my JHBuild test install (on the same Arch Linux machine). Maybe there are some packages which haven't been updated yet.

**Comment by manoevis** [comment]
how cloud I get my red fancy dot for close button back?
